from PyQt6 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 596)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label.setLineWidth(10)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.percentButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.percentButton.clicked.connect(lambda: self.press_it("%"))
        self.percentButton.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.cButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cButton.clicked.connect(lambda: self.press_it("C"))
        self.cButton.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.arrowButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.arrowButton.clicked.connect(lambda: self.remove_it())
        self.arrowButton.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.divideButton.clicked.connect(lambda: self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(275, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.nineButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nineButton.clicked.connect(lambda: self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(190, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.multipyButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.multipyButton.clicked.connect(lambda: self.press_it("*"))
        self.multipyButton.setGeometry(QtCore.QRect(275, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.multipyButton.setFont(font)
        self.multipyButton.setObjectName("multipyButton")
        self.sevenButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sevenButton.clicked.connect(lambda: self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.eightButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.eightButton.clicked.connect(lambda: self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.fiveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fiveButton.clicked.connect(lambda: self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(100, 280, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.minusButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minusButton.clicked.connect(lambda: self.press_it("-"))
        self.minusButton.setGeometry(QtCore.QRect(275, 280, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.sixButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sixButton.clicked.connect(lambda: self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(190, 280, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.fourButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fourButton.clicked.connect(lambda: self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 280, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.oneButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.oneButton.clicked.connect(lambda: self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.twoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.twoButton.clicked.connect(lambda: self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(100, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.threeButton.clicked.connect(lambda: self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(190, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.clicked.connect(lambda: self.press_it("+"))
        self.addButton.setGeometry(QtCore.QRect(275, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.plusminusButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.plusminusButton.clicked.connect(lambda: self.plus_minus_it())
        self.plusminusButton.setGeometry(QtCore.QRect(10, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setObjectName("plusminusButton")
        self.zeroButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.zeroButton.clicked.connect(lambda: self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(100, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.decimalButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.decimalButton.clicked.connect(lambda: self.dot_it())
        self.decimalButton.setGeometry(QtCore.QRect(190, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        self.equalButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.equalButton.clicked.connect(lambda: self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(275, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Let's do some math!
    def math_it(self):
        # Grab what's on the screen already
        screen = self.label.text()
        try:
            # Do the math
            answer = eval(screen)
            # Output answer to the screen
            self.label.setText(str(answer))
        except:
            # Output error to the screen
            self.label.setText("ERROR")

    # Change from positive/negative
    def plus_minus_it(self):
        # Grab what's on the screen already
        screen = self.label.text()
        if "-" in screen:
            self.label.setText(screen.replace("+",""))
        else:
            self.label.setText(f'-{screen}')

    # Remove character
    def remove_it(self):
        # Grab what's on the screen already
        screen = self.label.text()
        # Remove last item in list/string
        screen = screen[:-1]
        # Output back to the screen
        self.label.setText(screen)

    # Add a decimal
    def dot_it(self):
        screen = self.label.text()
        if screen[-1] == ".":
            pass
        else:
            self.label.setText(f'{screen}.')

    def press_it(self, pressed):
        if pressed == "C":
            self.label.setText("0")
        else:
            # Check to see if starts with 0 and delete 0
            if self.label.text() == "0":
                self.label.setText("")
            # Concatenate the pressed button with what was there already
            self.label.setText(f'{self.label.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label.setText(_translate("MainWindow", "0"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.arrowButton.setText(_translate("MainWindow", "<<"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.multipyButton.setText(_translate("MainWindow", "x"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.plusminusButton.setText(_translate("MainWindow", "+/-"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.equalButton.setText(_translate("MainWindow", "-="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
