# Form implementation generated from reading ui file 'dial.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(270, 234)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dial = QtWidgets.QDial(parent=self.centralwidget)
        # Set dial defaults
        #self.dial.setMinimum(10)
        #self.dial.setMaximum(360)
        self.dial.setRange(10,360)
        # Set default startup position
        #self.dial.setValue(50)
        # Set notches
        self.dial.setNotchesVisible(True)
        # Set color
        self.dial.setStyleSheet('background-color: blue')
        # Use dial
        self.dial.valueChanged.connect(lambda: self.dialer())
        self.dial.setGeometry(QtCore.QRect(30, 10, 201, 121))
        self.dial.setStyleSheet("QDial {\n"
"    background: qradialgradient(\n"
"        cx: 0.5, cy: 0.5, radius: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        stop: 0 #ffffff,\n"
"        stop: 1 #b0c4de\n"
"    );\n"
"    border: 3px solid #0077cc;\n"
"    border-radius: 50px;\n"
"}\n"
"\n"
"")
        self.dial.setObjectName("dial")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 140, 241, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 270, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Current Position: "))
    def dialer(self):
        #Grab current dial position
        value = self.dial.value()
        # Set label text
        self.label.setText(f'Current Position: {str(value)}')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
